import MediaGallery from "../components/gallery-deprecated";
import { GalleryContent } from "./localModelsGallery";
import { Image } from "antd";
import {
  type Model,
  model,
  type ModelsRequestOpts,
  type ModelVersion,
} from "../../modules/civitai-deprecated/models/models_endpoint";
import { extractFilenameFromUrl } from "#modules/civitai-deprecated/service/sharedUtils.js";

const modelData = model.assert({
  id: 2092400,
  name: "Hakuhou (Azur Lane) (2 outfit) | Goofy Ai",
  description:
    '<h3 id="private-commission-on-fiverr-get-early-access-to-my-upcoming-nsfw-lora-on-my-patreon.">Private commission on <a target="_blank" rel="ugc" href="https://www.fiverr.com/users/ashrafulalam03">fiverr </a><br /><span style="color:rgb(64, 192, 87)"><strong>Get early access to my upcoming NSFW Lora on my </strong></span><a target="_blank" rel="ugc" href="https://patreon.com/goofy_ai_"><span style="color:rgb(250, 82, 82)"><strong>Patreon</strong></span><span style="color:rgb(64, 192, 87)"><strong>.</strong></span></a></h3><h3 id="early-lora-share-on-discord-for-patreon."><span style="color:rgb(64, 192, 87)">early lora share on discord for patreon.</span></h3><h2 id="i-officially-host-and-maintain-all-my-models-on-tensor.art"><span style="color:rgb(250, 176, 5)"><strong>I officially host and maintain all my models on</strong></span><strong> </strong><a target="_blank" rel="ugc" href="https://tensor.art/u/597010577386112018"><strong>Tensor.art</strong></a></h2><p><span style="color:rgb(253, 126, 20)">I was hoping you could support my work by joining any one of them and get early access to all my upcoming loras and other perks, such as fan requests and a Discord role.</span></p><h2 id="join-my-discord-server"><strong>Join my </strong><a target="_blank" rel="ugc" href="https://discord.gg/waSD943d2R"><strong><u>Discord Server</u></strong></a></h2><ul><li><p>check the images for prompts</p></li><li><p>use lora at 0.7-1</p></li><li><p>Adetailer for faces</p></li><li><p>Img2img upscale</p></li><li><p>4x-ultra sharp</p></li><li><p>comment you idea or request</p></li></ul><p></p>',
  allowNoCredit: false,
  allowCommercialUse: ["RentCivit"],
  allowDerivatives: false,
  allowDifferentLicense: true,
  type: "LORA",
  minor: false,
  sfwOnly: false,
  poi: false,
  nsfw: true,
  nsfwLevel: 60,
  availability: "Public",
  cosmetic: null,
  supportsGeneration: true,
  stats: {
    downloadCount: 493,
    favoriteCount: 0,
    thumbsUpCount: 159,
    thumbsDownCount: 0,
    commentCount: 0,
    ratingCount: 0,
    rating: 0,
    tippedAmountCount: 0,
  },
  creator: {
    username: "Goofy_Ai",
    image:
      "https://image.civitai.com/xG1nkqKTMzGDvpLrqFT7WA/02604516-262f-4378-aeed-12d987e4da1b/width=96/Goofy_Ai.jpeg",
  },
  tags: ["anime", "character", "azur lane", "woman", "hakuhou"],
  modelVersions: [
    {
      id: 2367377,
      index: 0,
      name: "v1.0",
      baseModel: "Illustrious",
      baseModelType: "Standard",
      createdAt: "2025-11-01T18:57:13.313Z",
      publishedAt: "2025-11-01T19:00:22.744Z",
      status: "Published",
      availability: "Public",
      nsfwLevel: 60,
      trainedWords: [
        "hakuhou \\(azur lane\\), long hair, bare shoulders, black sash,  hair between eyes,  japanese clothes, kimono,  long hair between eyes, long sleeves, white mask, mask on head, pantyhose,  white hair, white kimono, white pantyhose, wide sleeves, yellow eyes",
        "hakuhou \\(floral ninja roleplay\\) \\(azur lane\\),yellow eyes,white hair, red rope, torn thighhighs, shibari over clothes, long hair,  bare shoulders, black thighhighs, red eyes, bow",
      ],
      covered: true,
      stats: {
        downloadCount: 493,
        ratingCount: 0,
        rating: 0,
        thumbsUpCount: 159,
        thumbsDownCount: 0,
      },
      files: [
        {
          id: 2258191,
          sizeKB: 56071.56640625,
          name: "hakuhou_azur_lane_ilxl_goofy.safetensors",
          type: "Model",
          pickleScanResult: "Success",
          pickleScanMessage: "No Pickle imports",
          virusScanResult: "Success",
          virusScanMessage: null,
          scannedAt: "2025-11-01T19:00:44.677Z",
          metadata: {
            format: "SafeTensor",
          },
          hashes: {
            AutoV1: "75DDE034",
            AutoV2: "2845AD4634",
            SHA256:
              "2845AD4634236D93AA20CFE22941B9E00AA0BAE281ACF90F44C295690374860F",
            CRC32: "1F5B17F5",
            BLAKE3:
              "13086B1450AE07161CC49509068DEF45FA06CF943D15B95F797B1F2F3ED09A31",
            AutoV3: "BE0D1DCD2F75",
          },
          downloadUrl: "https://civitai.com/api/download/models/2367377",
          primary: true,
        },
      ],
      images: [
        {
          url: "https://image.civitai.com/xG1nkqKTMzGDvpLrqFT7WA/1f147393-fc11-4a01-8d74-6fde6170ab90/original=true/108532342.mp4",
          nsfwLevel: 4,
          width: 464,
          height: 688,
          hash: "U00000fQfQfQfQfQfQfQfQfQfQfQfQfQfQfQ",
          type: "video",
          minor: false,
          poi: false,
          hasMeta: true,
          hasPositivePrompt: true,
          onSite: false,
          remixOfId: null,
          id: 108532342,
        },
        {
          url: "https://image.civitai.com/xG1nkqKTMzGDvpLrqFT7WA/6656b13a-f661-4d0a-893e-01c1d08b6f63/original=true/108532520.jpeg",
          nsfwLevel: 2,
          width: 1664,
          height: 2432,
          hash: "UDNl_T~p4,n#I9RPDgIU0LjbM}a~^+tQ9FRj",
          type: "image",
          minor: false,
          poi: false,
          hasMeta: true,
          hasPositivePrompt: true,
          onSite: false,
          remixOfId: null,
          id: 108532520,
        },
        {
          url: "https://image.civitai.com/xG1nkqKTMzGDvpLrqFT7WA/e4e4e729-c3eb-4e13-a455-71f69e639462/original=true/108532522.jpeg",
          nsfwLevel: 4,
          width: 1664,
          height: 2432,
          hash: "UROM,2IV?^%g_3t7%gx]x^V@slRjI;j[V@WB",
          type: "image",
          minor: false,
          poi: false,
          hasMeta: true,
          hasPositivePrompt: true,
          onSite: false,
          remixOfId: null,
          id: 108532522,
        },
        {
          url: "https://image.civitai.com/xG1nkqKTMzGDvpLrqFT7WA/611b46be-8fb4-4644-b5a9-784482bfff3b/original=true/108532523.jpeg",
          nsfwLevel: 2,
          width: 1664,
          height: 2432,
          hash: "UCLzgf00Ir$*?d=|=}i_BE=|Vrxb6,?H?Gt8",
          type: "image",
          minor: false,
          poi: false,
          hasMeta: true,
          hasPositivePrompt: true,
          onSite: false,
          remixOfId: null,
          id: 108532523,
        },
        {
          url: "https://image.civitai.com/xG1nkqKTMzGDvpLrqFT7WA/cdaf9dc3-903f-4989-8055-e5f2d526edcc/original=true/108532517.jpeg",
          nsfwLevel: 4,
          width: 1664,
          height: 2432,
          hash: "U3L|y50000.9MHg500-;00E+00IV00D%~XD%",
          type: "image",
          minor: false,
          poi: false,
          hasMeta: true,
          hasPositivePrompt: true,
          onSite: false,
          remixOfId: null,
          id: 108532517,
        },
        {
          url: "https://image.civitai.com/xG1nkqKTMzGDvpLrqFT7WA/aa9b685a-7abc-43ec-be62-fdca9ff8d01c/original=true/108532516.jpeg",
          nsfwLevel: 4,
          width: 1664,
          height: 2432,
          hash: "UJN]z.~W%Mt7R*t7n4s:4.nhM{Rk?uxuM|%M",
          type: "image",
          minor: false,
          poi: false,
          hasMeta: true,
          hasPositivePrompt: true,
          onSite: false,
          remixOfId: null,
          id: 108532516,
        },
        {
          url: "https://image.civitai.com/xG1nkqKTMzGDvpLrqFT7WA/c17c8abe-4b37-4d8d-989a-d88301983658/original=true/108532519.jpeg",
          nsfwLevel: 4,
          width: 1664,
          height: 2432,
          hash: "UVO:U_V@.Txu.Sof%MozENt7xtWB^+t7IURj",
          type: "image",
          minor: false,
          poi: false,
          hasMeta: true,
          hasPositivePrompt: true,
          onSite: false,
          remixOfId: null,
          id: 108532519,
        },
        {
          url: "https://image.civitai.com/xG1nkqKTMzGDvpLrqFT7WA/2cc19fd7-eb1e-4045-81c8-9805251e3503/original=true/108532512.jpeg",
          nsfwLevel: 4,
          width: 1664,
          height: 2432,
          hash: "UQOy-LD%.S?b_NM{RjtlXnRP-pIAtlt7RPxt",
          type: "image",
          minor: false,
          poi: false,
          hasMeta: true,
          hasPositivePrompt: true,
          onSite: false,
          remixOfId: null,
          id: 108532512,
        },
        {
          url: "https://image.civitai.com/xG1nkqKTMzGDvpLrqFT7WA/d33e4f37-a938-480e-86a9-4385d7e337a4/original=true/108532449.jpeg",
          nsfwLevel: 4,
          width: 1664,
          height: 2432,
          hash: "UEKTlQ9[000KEe~qZ}D%00TL^*IU^+0Ls,xu",
          type: "image",
          minor: false,
          poi: false,
          hasMeta: true,
          hasPositivePrompt: true,
          onSite: false,
          remixOfId: null,
          id: 108532449,
        },
        {
          url: "https://image.civitai.com/xG1nkqKTMzGDvpLrqFT7WA/3ef6cad2-7a3a-4422-af2d-58ea3e8ef179/original=true/108532442.jpeg",
          nsfwLevel: 2,
          width: 1664,
          height: 2432,
          hash: "UEMGu300Zf~qv|S48_NeD$V?%g-;?^s;IA-p",
          type: "image",
          minor: false,
          poi: false,
          hasMeta: true,
          hasPositivePrompt: true,
          onSite: false,
          remixOfId: null,
          id: 108532442,
        },
        {
          url: "https://image.civitai.com/xG1nkqKTMzGDvpLrqFT7WA/6b53f2fd-ec0e-4558-9012-916850e3b7cc/original=true/108532448.jpeg",
          nsfwLevel: 16,
          width: 1664,
          height: 2432,
          hash: "UJHBVq9aIo%g0et74ntR~WVsI:xa01bb%LWB",
          type: "image",
          minor: false,
          poi: false,
          hasMeta: true,
          hasPositivePrompt: true,
          onSite: false,
          remixOfId: null,
          id: 108532448,
        },
        {
          url: "https://image.civitai.com/xG1nkqKTMzGDvpLrqFT7WA/a946c7e6-ede1-4595-b0be-5b96206de720/original=true/108532451.jpeg",
          nsfwLevel: 4,
          width: 1664,
          height: 2432,
          hash: "UELz8Oxt56_N^jxas+?a0MIU8_9F$f4:WBD*",
          type: "image",
          minor: false,
          poi: false,
          hasMeta: true,
          hasPositivePrompt: true,
          onSite: false,
          remixOfId: null,
          id: 108532451,
        },
        {
          url: "https://image.civitai.com/xG1nkqKTMzGDvpLrqFT7WA/7921fc7e-3fe9-45c6-907b-c0e60f3865c6/original=true/108532447.jpeg",
          nsfwLevel: 4,
          width: 1664,
          height: 2432,
          hash: "U7N0SU00Po~C1K000eR+00?^4T.8D4?G4T.8",
          type: "image",
          minor: false,
          poi: false,
          hasMeta: true,
          hasPositivePrompt: true,
          onSite: false,
          remixOfId: null,
          id: 108532447,
        },
        {
          url: "https://image.civitai.com/xG1nkqKTMzGDvpLrqFT7WA/62dc05e3-98ef-4614-ac15-3a6fbf247a67/original=true/108532443.jpeg",
          nsfwLevel: 4,
          width: 1664,
          height: 2432,
          hash: "UlN9@5~qS~%2yD-;Sht7S$ofr?V@t6RPWBaz",
          type: "image",
          minor: false,
          poi: false,
          hasMeta: true,
          hasPositivePrompt: true,
          onSite: false,
          remixOfId: null,
          id: 108532443,
        },
        {
          url: "https://image.civitai.com/xG1nkqKTMzGDvpLrqFT7WA/15fa99d9-00f9-4c4f-8a0d-0a5177ab9fa7/original=true/108532454.jpeg",
          nsfwLevel: 4,
          width: 1664,
          height: 2432,
          hash: "UcKd_EWB_Nxu~qs:M{t7.8oeM{ay-;ofxuay",
          type: "image",
          minor: false,
          poi: false,
          hasMeta: true,
          hasPositivePrompt: true,
          onSite: false,
          remixOfId: null,
          id: 108532454,
        },
        {
          url: "https://image.civitai.com/xG1nkqKTMzGDvpLrqFT7WA/38550828-6607-49ea-98bc-1686c583a57c/original=true/108532515.jpeg",
          nsfwLevel: 4,
          width: 1664,
          height: 2432,
          hash: "U5K,y;00009k00o=?cj20w~A9I?uIt$0?bXn",
          type: "image",
          minor: false,
          poi: false,
          hasMeta: true,
          hasPositivePrompt: true,
          onSite: false,
          remixOfId: null,
          id: 108532515,
        },
        {
          url: "https://image.civitai.com/xG1nkqKTMzGDvpLrqFT7WA/582ee3ce-de92-42db-bec1-d4d2313b3b60/original=true/108532521.jpeg",
          nsfwLevel: 4,
          width: 1664,
          height: 2432,
          hash: "UlOpc5%M_NRj?vayayoLtRWBRjtRxuazWBNG",
          type: "image",
          minor: false,
          poi: false,
          hasMeta: true,
          hasPositivePrompt: true,
          onSite: false,
          remixOfId: null,
          id: 108532521,
        },
        {
          url: "https://image.civitai.com/xG1nkqKTMzGDvpLrqFT7WA/d72cce1b-ae15-4667-9c7f-0f031e16c672/original=true/108532518.jpeg",
          nsfwLevel: 16,
          width: 1664,
          height: 2432,
          hash: "UPK^Qy-;JnX8?w-;ofWVE1t7M_oL0KM{M_Io",
          type: "image",
          minor: false,
          poi: false,
          hasMeta: true,
          hasPositivePrompt: true,
          onSite: false,
          remixOfId: null,
          id: 108532518,
        },
        {
          url: "https://image.civitai.com/xG1nkqKTMzGDvpLrqFT7WA/5867d7ea-6b06-41c8-814d-4e13a1977c82/original=true/108532524.jpeg",
          nsfwLevel: 4,
          width: 1664,
          height: 2432,
          hash: "UEMZdi^%Eu^+.8NHIAS%4.RlD*%M_Ms+-og3",
          type: "image",
          minor: false,
          poi: false,
          hasMeta: true,
          hasPositivePrompt: true,
          onSite: false,
          remixOfId: null,
          id: 108532524,
        },
        {
          url: "https://image.civitai.com/xG1nkqKTMzGDvpLrqFT7WA/a4c3ee43-b9fa-4560-b46e-b9dc4dd675e9/original=true/108532513.jpeg",
          nsfwLevel: 4,
          width: 1664,
          height: 2432,
          hash: "UVNv-~xa?^%MtRaeD%ayELayRPof?HjsIUV[",
          type: "image",
          minor: false,
          poi: false,
          hasMeta: true,
          hasPositivePrompt: true,
          onSite: false,
          remixOfId: null,
          id: 108532513,
        },
      ],
      downloadUrl: "https://civitai.com/api/download/models/2367377",
      description: null,
    },
  ],
});

const dbModelData = {
  id: 2092400,
  name: "Hakuhou (Azur Lane) (2 outfit) | Goofy Ai",
  creatorId: 7,
  typeId: 6,
  nsfw: true,
  nsfwLevel: 60,
  createdAt: new Date("2025-11-20T11:07:56.989Z"),
  updatedAt: new Date("2025-11-20T11:07:56.989Z"),
  previewFile: "108532342.mp4",
  modelVersions: [
    {
      id: 2367377,
      modelId: 2092400,
      name: "v1.0",
      baseModelId: 3,
      baseModelTypeId: 1,
      publishedAt: new Date("2025-11-01T19:00:22.744Z"),
      nsfwLevel: 60,
      createdAt: new Date("2025-11-20T11:07:57.000Z"),
      updatedAt: new Date("2025-11-20T11:07:57.000Z"),
    },
  ],
  tags: [
    {
      id: 1,
      name: "anime",
    },
    {
      id: 12,
      name: "woman",
    },
    {
      id: 101,
      name: "character",
    },
    {
      id: 132,
      name: "azur lane",
    },
    {
      id: 3360,
      name: "hakuhou",
    },
  ],
  creator: {
    id: 7,
    username: "Goofy_Ai",
    link: null,
    image:
      "https://image.civitai.com/xG1nkqKTMzGDvpLrqFT7WA/02604516-262f-4378-aeed-12d987e4da1b/width=96/Goofy_Ai.jpeg",
  },
  type: {
    id: 6,
    name: "LORA",
  },
};

function LocalModelCardContentLeftSide({
  modelVersion,
}: {
  modelVersion: ModelVersion;
}) {
  return (
    <>
      <div>
        {modelVersion.images[0]?.url ? (
          <MediaGallery
            mediaArray={modelVersion.images.map(
              (i) =>
                `${location.origin}/civitai/local/media/preview?previewFile=${extractFilenameFromUrl(
                  i.url
                )}`
            )}
          />
        ) : (
          <img title="Have no preview" />
        )}
      </div>
    </>
  );
}

export default function GalleryTestPage() {
  return (
    <GalleryContent
      models={[dbModelData]}
      ModelCardContentLeftSide={LocalModelCardContentLeftSide}
    />
  );
}
